
name: Build libcudf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
 
  build:
    
    runs-on: self-hosted
    container:
      image: nvidia/cuda:11.0.3-devel-ubuntu20.04
      options: --gpus all
      
    env:
      CUDF_HOME: cudf
      DEBIAN_FRONTEND: 'noninteractive'
    
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: |
          apt-get update -y
          apt-get install -y sudo software-properties-common dialog apt-utils tzdata git
        
      # Runs a single command using the runners shell
      - name: Clone cudf repository
        run: |
          git clone https://github.com/rapidsai/cudf.git $CUDF_HOME
          cd $CUDF_HOME
          git submodule update --init --remote --recursive
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: cudf_dev
          environment-file: cudf/conda/environments/cudf_dev_cuda11.0.yml

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo bash cudf/build.sh libcudf
